version: "3.8"

services:
  protogen:
    build:
      context: ./docker
      dockerfile: proto.Dockerfile
      args:
        PLATFORM: ${PLATFORM}
        PROTOC_VERSION: ${PROTOC_VERSION}
    working_dir: /source
    volumes:
      - ./../pb:/source
    command: >
      /bin/sh -c "protoc *.proto --proto_path=. \
      --go_out=. --go_opt=module=github.com/ngtrdai197/go-rabbitmq/pb \
      --go-grpc_out=. --go-grpc_opt=module=github.com/ngtrdai197/go-rabbitmq/pb"
